// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { Event } from "./Event";
import type { Trigger } from "./Trigger";

export interface Chain { title: string, cooldown: number, trigger: Trigger | null, events: Record<string, Event>, effects: Record<string, Effect>, autoSelect: boolean | null, }