// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeOperation } from "./ChangeOperation";
import type { ChangeTarget } from "./ChangeTarget";
import type { EffectType } from "./EffectType";

export interface Effect { description: string | null, operation: ChangeOperation, target: ChangeTarget, value: number, type: EffectType, }