// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerComparator } from "./TriggerComparator";
import type { TriggerTarget } from "./TriggerTarget";

export interface Trigger { comparator: TriggerComparator, target: TriggerTarget, value: number, }